name: core
description: A new Flutter package project.
version: 0.0.1
author: Toshi Ossada
homepage: https://www.ioasys.com.br/

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  commons_dependencies:
    git:
      url: https://github.com/toshiossada/microapp_commons_dependencies.git
      ref: v1.0.0
  module_splash:
    git:
      url: https://github.com/toshiossada/micoappp_module_splash.git
      ref: v1.0.0
  module_login:
    git:
      url: https://github.com/toshiossada/micoappp_module_login.git
      ref: v1.0.0
  module_home:
    git:
      url: https://github.com/toshiossada/microapp_module_home.git
      ref: v1.0.1  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.1
  flutter_modular_test: ^1.0.1
  hive_generator: ^1.1.0
  http_mock_adapter: ^0.2.1
  mockito: ^5.0.5
  triple_test: ^0.0.5  
  effective_dart: ^1.3.1

flutter:
